on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{secrets.SONAR_URL}}
        login: ${{secrets.SONAR_USER}}
        password: ${{secrets.SONAR_PASSWORD}}
        projectKey: "spiracle"
        projectName: "spiracle"
        projectVersion: "1.4.0"
